#ifndef __RT_655_H_
#define __RT_655_H_

//flove122309_S
#define RT655_RESET						0X00			//RESET
#define RT655_MASTER_VOL				0X02			//MASTER VOLUME
#define RT655_MONO_OUT_VOL				0X06			//MONO OUT VOLUME
#define RT655_PCBEEP_VOL				0X0A			//PC BEEP VOLUME
#define RT655_PHONE_VOL					0X0C			//PHONE VOLUME
#define RT655_MIC_VOL					0X0E			//MIC VOLUME
#define RT655_LINEIN_VOL				0X10			//LINE IN VOLUME
#define RT655_CD_VOL					0X12			//CD VOLUME
#define RT655_AUX_VOL					0X16			//AUX VOLUME
#define RT655_FRONT_DAC_VOL				0X18			//PCM OUT VOLUME
#define RT655_REC_SEL					0X1A			//RECORD SELECT
#define RT655_REC_GAIN					0X1C			//RECORD GAIN
#define RT655_GEN_PUR					0X20			//GENERAL PURPOSE REGISTER
#define RT655_AUDIO_PAGING				0X24			//AUDIO INTERRUPT AND PAGING MECHANISM
#define RT655_PWR_CTRL					0X26			//POWERDOWN CONTROL/STAUTS
#define RT655_EXT_ID					0X28			//EXTENDED AUDIO ID
#define RT655_EXT_STAUS					0X2A			//EXTENDED AUDIO STATUS AND CONTROL REGISTER 
#define RT655_PCM_FR_SR					0X2C			//PCM FRONT/CENTER OUTPUT SAMPLE RATE
#define RT655_PCM_SUR_SR				0X2E			//PCM SURROUND OUTPUT SAMPLE RATE
#define RT655_PCM_LFE_SR				0X30			//PCM LFE OUTPUT SAMPLE RATE
#define RT655_PCM_IN_SR					0X32			//ADC PCM INPUT SAMPLE RATE
#define RT655_CEN_LFE_VOL				0X36			//LFE/CENTER MASTER VOLUME
#define RT655_SUR_VOL					0X38			//SURROUND MASTER VOLUME
#define RT655_SPDIF_CTRL				0X3A			//SPDIF OUTPUT CHANNEL STATUS AND CONTROL
#define RT655_SPDIF_IN_STATUS_1			0X60			//SPDIF INPUT CHANNEL STATUS 1
#define RT655_SPDIF_IN_STATUS_2			0X62			//SPDIF INPUT CHANNEL STATUS 2
#define RT655_SUR_DAC_VOL				0X64			//SURROUND DAC VOLUME
#define RT655_CEN_LFE_DAC_VOL			0X66			//RESET CODEC TO DEFAULT
#define RT655_SENSE_SEN_CTRL			0X68			//SENSE SENSITIVITY CONTROL
#define RT655_MULT_CHAN_CTRL			0X6A			//MULTI CHANNEL CONTROL
#define RT655_PRODUCT_NUM				0X6E			//PRODUCT NUMBER
#define RT655_GPIO_INT_CTRL_STATUS		0X78			//GPIO(JD) INTERRUPT CONTROL & STATUS	
#define RT655_EXT_CTRL					0X7A			//EXTEND CONTROL 	
#define RT655_VEDNOR_ID					0X7C			//RESET CODEC TO DEFAULT
#define RT655_VENDOR_ID2				0X7E			//RESET CODEC TO DEFAULT
//flove122309_E

extern int rt655_reset(struct snd_soc_codec *codec, int try_warm);

extern struct snd_soc_codec_device soc_codec_dev_rt655;
extern struct snd_soc_dai rt655_dai;
#endif
