include $(srctree)/$(subst ",,$(CONFIG_MV_HAL_RULES_PATH))
# Objects list
obj-$(CONFIG_MV_INCLUDE_CESA) += mvCesa.o
obj-$(CONFIG_MV_INCLUDE_CESA) += mvCesaDebug.o
obj-$(CONFIG_MV_INCLUDE_CESA) += mvMD5.o
obj-$(CONFIG_MV_INCLUDE_CESA) += mvSHA1.o
obj-$(CONFIG_MV_CESA_TEST) += mvCesaTest.o

