# Dove Machine Support
snd-soc-dovedb-objs := dove_db.o
snd-soc-dove-db-b-objs := dove_db_b.o
snd-soc-dove-avng-objs := dove_ac97_avng.o

obj-$(CONFIG_SND_DOVE_SOC_DB) += snd-soc-dovedb.o
obj-$(CONFIG_SND_DOVE_SOC_DB_B) += snd-soc-dove-db-b.o

obj-$(CONFIG_SND_DOVE_SOC_MRVL_AUDIO) 	+= ../../../arch/arm/plat-orion/mv_hal_drivers/mv_drivers_lsp/mv_audio_soc/
obj-$(CONFIG_SND_DOVE_SOC_AC97_AVD1) += snd-soc-dove-avng.o


