# Display drivers

display-objs			:= display-sysfs.o

obj-$(CONFIG_DISPLAY_SUPPORT)	+= display.o

obj-$(CONFIG_CH7025_COMPOSITE)  += ch7025_composite.o
obj-$(CONFIG_KG2_ANX7150)	+= kg2/
obj-$(CONFIG_KG2_ANX7150)	+= ANX7150/
obj-$(CONFIG_ADI9889)		+= adi9889/
obj-$(CONFIG_THS8200)		+= ths_8200.o
