#
# Makefile for HDMI transmitters that connect to Dove framebuffer
#

obj-$(CONFIG_ADI9889) += adi9889.o
adi9889-objs := AD9889_interrupt_handler.o AD9889_setup.o edid_parse.o reg_handler.o adi9889_setup.o
